nodeLinker: node-modules

npmRegistries:
  //gitlab.addamant-work.ru/api/v4/packages/npm:
    npmAlwaysAuth: true
    npmAuthToken: "access token"

npmScopes:
  addamant-ui:
    npmRegistryServer: "https://gitlab.addamant-work.ru/api/v4/packages/npm"
